package s4y.itag.ble.internal;

public enum BLEConnectionError {
    TIMEOUT,
    NO_PERIPHERAL,
    BAD_UUID,
    NO_IMMEDIATE_ALERT_SERVICE,
    NO_FIND_ME_ALERT_SERVICE,
    NO_IMMEDIATE_ALERT_CHARACTERISTIC,
    NO_FIND_ME_ALERT_CHARACTERISTIC
}
